[package]
name = "geek-qq"
version = "0.1.0"
authors = ["Artin <lengthmin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
[profile.release]
opt-level = 3
